name: weather_forecast
description: Weather app dengan gradient sky lembut, hourly forecast, dan weekly forecast.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
